# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paint_hydro',
                'doc_host': 'https://nesar.github.io',
                'git_url': 'https://github.com/nesar/paint_hydro',
                'lib_path': 'paint_hydro'},
  'syms': {'paint_hydro.core': {'paint_hydro.core.foo': ('core.html#foo', 'paint_hydro/core.py')}}}
