# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_load.ipynb.

# %% auto 0
__all__ = ['cosmology_model', 'load_sfh']

# %% ../nbs/01_load.ipynb 4
import numpy as np
import matplotlib.pylab as plt
from colossus.cosmology import cosmology
import haccytrees as haccT

# %% ../nbs/01_load.ipynb 6
def cosmology_model(sim_name): # simulation name
    ''' 
    Cosmic Age of all snapshots
    '''
    sim = haccT.Simulation.simulations[sim_name]

    cosmo = cosmology.setCosmology(sim_name, dict(
        flat=True,
        H0=sim.cosmo.h*100,
        Om0=sim.cosmo.Omega_m,
        Ob0=sim.cosmo.Omega_b,
        sigma8=sim.cosmo.s8,
        ns=sim.cosmo.ns
    ))
    return cosmo

# %% ../nbs/01_load.ipynb 7
def load_sfh(hacc_sfh_file): # input text file
    '''
    Load SFH text files
    '''
    cosmo = cosmology_model("AlphaQ")
    hacc_hydro_sm = np.loadtxt(hacc_sfh_file)
    hydro_sm = hacc_hydro_sm[:, 0]
    
    for indx in range(1, hydro_sm.shape[0]):
        if (hydro_sm[indx] > hydro_sm[indx-1]) :
            hydro_sm[indx] = hydro_sm[indx-1]-100
    
    hydro_tt = cosmo.age(z = hacc_hydro_sm[:, 1])
    return hydro_sm[::-1], hydro_tt[::-1]
