# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_metal.ipynb.

# %% auto 0
__all__ = ['logZfit']

# %% ../nbs/02_metal.ipynb 4
import matplotlib.pylab as plt
import numpy as np

# %% ../nbs/02_metal.ipynb 5
def logZfit(logM, # log stellar mass
            redshift): # redshift
    '''
    returns log(Metallicity)
    
    Fitting done in Projects/SPHEREx/MAH/stellar_metal_obs.py

    '''
    a, b, c = 0.3265417, -0.07960499, -3.37447516

    logZ = a*logM + b*(redshift) + c
    return logZ
